services:
  mysql:
    image: mysql:8.0
    container_name: proyecto_mysql_final
    restart: always ##unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  backend:
    image: patriciavargash1/vargaschoque_backend:v1
    container_name: proyecto_backend
    restart: always ##unless-stopped
    ports:
      - '4000:4000'
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql
  frontend:
    image: patriciavargash1/vargaschoque_frontend:v1
    container_name: proyecto_frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  db_data:
